
    create table action_figures (
        depth float(53) not null,
        height float(53) not null,
        width float(53) not null,
        product_id bigint not null,
        brand varchar(255) not null,
        material varchar(255) not null,
        primary key (product_id)
    );

    create table board_games (
        average_play_time integer,
        max_players integer not null,
        min_players integer not null,
        recommended_age integer,
        product_id bigint not null,
        brand varchar(255) not null,
        primary key (product_id)
    );

    create table comics (
        pages integer not null,
        volume_number integer,
        product_id bigint not null,
        author varchar(255) not null,
        publisher varchar(255) not null,
        primary key (product_id)
    );

    create table error_message (
        message varchar(100) not null,
        code varchar(255) not null,
        primary key (code)
    );

    create table products (
        price numeric(10,2) not null,
        release_date date,
        stock_quantity integer not null,
        weight float(53),
        id bigint generated by default as identity,
        description TEXT,
        image_url varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists action_figures 
       add constraint FK2ghymkb7y2qrn220muug2qyim 
       foreign key (product_id) 
       references products;

    alter table if exists board_games 
       add constraint FKbl9715l6k58gjfxkjwv3xkqs2 
       foreign key (product_id) 
       references products;

    alter table if exists comics 
       add constraint FK3eylnxym8v2hqrc9dpkykwn36 
       foreign key (product_id) 
       references products;
