
    create table action_figures (
        depth float(53) not null,
        height float(53) not null,
        width float(53) not null,
        product_id bigint not null,
        brand varchar(255) not null,
        material varchar(255) not null,
        primary key (product_id)
    );

    create table board_games (
        average_play_time integer,
        max_players integer not null,
        min_players integer not null,
        recommended_age integer,
        product_id bigint not null,
        brand varchar(255) not null,
        primary key (product_id)
    );

    create table cart_items (
        quantity integer not null,
        cart_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id)
    );

    create table carts (
        id bigint generated by default as identity,
        user_id bigint not null unique,
        primary key (id)
    );

    create table comics (
        pages integer not null,
        volume_number integer,
        product_id bigint not null,
        author varchar(255) not null,
        publisher varchar(255) not null,
        primary key (product_id)
    );

    create table error_message (
        message varchar(100) not null,
        code varchar(255) not null,
        primary key (code)
    );

    create table order_items (
        price_at_purchase numeric(10,2) not null,
        quantity integer not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        primary key (id)
    );

    create table orders (
        total_price numeric(10,2) not null,
        id bigint generated by default as identity,
        order_date timestamp(6) not null,
        user_id bigint not null,
        status varchar(30) not null check ((status in ('PENDING','PAID','SHIPPED','DELIVERED','CANCELLED'))),
        primary key (id)
    );

    create table products (
        price numeric(10,2) not null,
        release_date date,
        stock_quantity integer not null,
        weight float(53),
        id bigint generated by default as identity,
        product_type varchar(30) not null check ((product_type in ('ACTION_FIGURE','BOARD_GAME','COMIC'))),
        description TEXT,
        image_url varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table users (
        is_admin boolean not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists action_figures 
       add constraint FK2ghymkb7y2qrn220muug2qyim 
       foreign key (product_id) 
       references products;

    alter table if exists board_games 
       add constraint FKbl9715l6k58gjfxkjwv3xkqs2 
       foreign key (product_id) 
       references products;

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK1re40cjegsfvw58xrkdp6bac6 
       foreign key (product_id) 
       references products;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists comics 
       add constraint FK3eylnxym8v2hqrc9dpkykwn36 
       foreign key (product_id) 
       references products;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;
